"""Tests for SQLAlchemy models."""
import pytest
from decimal import Decimal
from datetime import datetime

from app.models import Instrument, InstrumentPriceHistory


class TestInstrumentModel:
    """Tests for Instrument model."""

    def test_instrument_creation(self):
        """Test creating an instrument."""
        instrument = Instrument(
            ticker="AAPL",
            name="Apple Inc.",
            asset_class="STOCK",
            bid=Decimal("150.00"),
            ask=Decimal("150.50"),
        )
        assert instrument.ticker == "AAPL"
        assert instrument.name == "Apple Inc."
        assert instrument.asset_class == "STOCK"
        assert instrument.bid == Decimal("150.00")
        assert instrument.ask == Decimal("150.50")

    def test_instrument_mid_price(self):
        """Test mid_price calculation (database-generated)."""
        instrument = Instrument(
            ticker="AAPL",
            bid=Decimal("100.00"),
            ask=Decimal("102.00"),
        )
        # mid_price is generated by database, just verify attributes exist
        assert instrument.bid == Decimal("100.00")
        assert instrument.ask == Decimal("102.00")

    def test_instrument_without_optional_fields(self):
        """Test instrument with minimal required fields."""
        instrument = Instrument(ticker="MSFT")
        assert instrument.ticker == "MSFT"
        assert instrument.bid is None
        assert instrument.ask is None

    def test_instrument_ticker_uniqueness(self):
        """Test that ticker should be unique (constraint defined in model)."""
        # This test documents the constraint; actual enforcement is database-level
        instrument1 = Instrument(ticker="AAPL", name="Apple")
        instrument2 = Instrument(ticker="AAPL", name="Apple Clone")
        
        # Both can be created in memory; database would enforce uniqueness
        assert instrument1.ticker == instrument2.ticker


class TestInstrumentPriceHistoryModel:
    """Tests for InstrumentPriceHistory model."""

    def test_price_history_creation(self):
        """Test creating a price history record."""
        instrument = Instrument(ticker="AAPL", name="Apple")
        history = InstrumentPriceHistory(
            instrument=instrument,
            timestamp=datetime(2024, 1, 15, 14, 30, 0),
            open=Decimal("150.00"),
            high=Decimal("151.50"),
            low=Decimal("149.00"),
            close=Decimal("150.50"),
            volume=1000000,
        )
        assert history.open == Decimal("150.00")
        assert history.high == Decimal("151.50")
        assert history.low == Decimal("149.00")
        assert history.close == Decimal("150.50")
        assert history.volume == 1000000
        assert history.instrument.ticker == "AAPL"

    def test_price_history_bar_sequence(self):
        """Test OHLCV sequence validity."""
        history = InstrumentPriceHistory(
            instrument=Instrument(ticker="MSFT"),
            timestamp=datetime.utcnow(),
            open=Decimal("100.00"),
            high=Decimal("105.00"),
            low=Decimal("99.00"),
            close=Decimal("102.00"),
            volume=5000000,
        )
        # High >= Open, Close, Low and Low <= Open, Close
        assert history.high >= history.open
        assert history.high >= history.close
        assert history.low <= history.open
        assert history.low <= history.close

    def test_price_history_without_volume(self):
        """Test price history with zero or null volume."""
        history = InstrumentPriceHistory(
            instrument=Instrument(ticker="GOOG"),
            timestamp=datetime.utcnow(),
            open=Decimal("100.00"),
            high=Decimal("101.00"),
            low=Decimal("99.00"),
            close=Decimal("100.50"),
            volume=0,
        )
        assert history.volume == 0
